name: Gitee sync

on: [push]

jobs:
  gitee-push:
    runs-on: windows-2019
    env:
      GITEE_USERNAME: ${{ secrets.GITEE_USERNAME }}
      GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 100
      
      - name: Push to gitee
        run: |
          git remote add gitee "https://${{ env.GITEE_USERNAME }}:${{ env.GITEE_TOKEN }}@gitee.com/${{ github.repository }}.git"
          git push --force gitee "${{ github.ref }}"
          git remote remove gitee


    